version: '3.8'

services:
  directorialumnes:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5050:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped
    container_name: directorialumnes_web
